# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    image: node:20.10.0
    container_name: nest-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: sh -c "pnpm install && pnpm start:prod"