appName: admin-app

db:
  mysql:
    type: mysql
    username: root
    password: example

  mongodb:
    type: mongodb
    uri: mongodb://192.168.137.128:27017

log:
  on: true
  consoleLevel: verbose
  fileLevel: info
  dir: D:\Coding_Personal\nest\learn\nest-demo\logs
  filename: '%DATE%.log'
  max_size: 100
  max_backups: 10
  max_age: 7
  compress: true